spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gymdaus?useSSL=false&useUnicode=true
    #    url: jdbc:mysql://node34473-dusheff.es-1.axarnet.cloud:3306/damian
    username: root
    password: root
  #    password: GNSpby97452
  messages:
    basename: templates/languages/messages
    encoding: UTF-8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      location: uploads